name: Fetch Runner

on:
  workflow_dispatch:  # Allow manual runs

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # Automatically stop after 5 hours

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust based on your script requirements

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp aiofiles asyncio itertools requests

    - name: Run Fetch Script
      id: run-script
      run: |
        echo "Starting fetch script..."
        python auth_v2.py
      timeout-minutes: 295  # Timeout slightly less than the max duration to ensure cleanup

    - name: Commit Progress
      if: always()
      run: |
        echo "Committing progress..."
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Save progress files [$(date)]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token to authenticate the push

    - name: Trigger workflow on main branch
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/main.yml/dispatches \
          -d '{"ref":"main"}'
